name: Update databricks Repos on PRs

on:
 pull_request:

jobs:
 build:
  runs-on: ubuntu-latest

  steps:

    - name: setup python
    - uses: actions/setup-python@v2 actions/setup-python@v4
      with:
        python-version: 3.8 #install the python version needed

    - name: execute py
      env:
        DATABRICKS_HOST: https://3974167210227564.4.gcp.databricks.com/
        DATABRICKS_TOKEN: dapice8cfd453238dac403facb2fa9d9ae4e
      run: |
        python -m pip install --upgrade databricks-cli
        python setup.py install
        python setup.py bdist_wheel
        databricks fs cp --overwrite --recursive dist/ dbfs:/FileStore/libraries/bancor_etl
        databricks repos update --repo-id 265351023196717 --branch main
