name: Update databricks Repos on PRs


on:
 pull_request:

jobs:
 build:
  runs-on: ubuntu-latest

  steps:
    - name: setup python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8 #install the python version needed

    - name: execute py
      env:
        DATABRICKS_HOST: $(DATABRICKS_HOST)
        DATABRICKS_TOKEN: $(DATABRICKS_TOKEN)
        DATABRICKS_REPO_ID: $(DATABRICKS_REPO_ID)
      run: |
        python -m pip install --upgrade databricks-cli
        databricks repos update --repo-id "DATABRICKS_REPO_ID" --branch main
